clamp_control_node:
  plc_ip: "172.31.1.160"
  plc_db_number: 2
  plc_rack: 0
  plc_slot: 1

global_params:
    tsub_relative_rotation: "flexrowick/clamp_relative_rotation"
    tsub_absolute_rotation: "flexrowick/clamp_relative_rotation"
    tsub_calibration_command: "flexrowick/calibration_done_cmd"
